### ISSUE TITLE
Translation setting gets reset after each silence

### ISSUE THREAD

**Issue by SlavikCA** [QuentinFuxa/whisper_streaming_web#306]
I built and started WLK on Ubuntu with Nvidia RTX 4090:

sudo docker run  --rm -v /home/slavik/.cache:/root/.cache --gpus "device=0" --name wlk1 -p 8000:8000 wlk216 --model large-v3 --language ru --direct-english-translation

I found, that when it starts working, - it works great.
But after first pause, after silence - it start outputting some numbers (timestamps?) and then sometimes switch to original language (RU):

<img width="714" height="410" alt="Image" src="https://github.com/user-attachments/assets/210db4b6-0415-4c66-b84c-063f071569d9" />

If I stop and start again - first seconds (until silence) it works great again.

Logs:
```
=================================================
Faster-Whisper not found. Consider installing faster-whisper for better performance: `pip install faster-whisper`
==================================================
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     192.168.0.241:52449 - "WebSocket /asr" [accepted]
INFO:whisperlivekit.basic_server:WebSocket connection opened.
INFO:     connection open
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=1.44s | + Silence of = 1.44s
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=1.34s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.13s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.13s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.14s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.14s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.15s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.14s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.15s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.17s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.16s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.16s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.16s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.15s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.17s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.18s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.19s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.19s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.07s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.07s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.10s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.10s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.10s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.01s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s | + Silence starting | last_end = 5.48 |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.54s | + Silence of = 0.54s | last_end = 6.14 |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.03s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.03s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.03s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.03s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.05s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.05s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.07s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.10s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.11s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.13s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.13s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.14s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.02s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.06s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.08s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.10s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.12s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.13s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.13s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.14s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.16s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.18s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.19s | + Silence starting | last_end = 9.2 |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=2.28s | + Silence of = 2.15s | last_end = 9.58 |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.13s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.14s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.14s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.14s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.16s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.17s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.17s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.20s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.21s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.21s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.23s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.23s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.25s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.15s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.17s | + Silence starting | last_end = 13.32 |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.85s | + Silence of = 0.72s | last_end = 13.32 |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.13s |
```

**Comment by SlavikCA** [comment]
When testing with `--target-language en` - there is no such problem. But looks like the quality of translation RU -> EN is poor.

It looks like `--direct-english-translation` has better quality of translation (when it works).

**Comment by QuentinFuxa** [comment]
found the root cause - --direct-english-translation was never actually passing task=translate to the whisper backends in localagreement mode. it only changed the tokenizer language to english but whisper kept transcribing instead of translating. after silence (context reset), there was no english context left so it reverted fully to the source language.

fixed in 8923337 + aded164 (simulstreaming had a similar bug where task was passed as a boolean instead of the string 'translate')

**Comment by SlavikCA** [comment]
<img width="814" height="539" alt="Image" src="https://github.com/user-attachments/assets/48df7a33-0292-4a01-aa96-ba090d00958e" />

tested 0.2.18

No changes, issue still happens.

```
docker run --rm --name wlk \
>  -v /home/slavik/.cache:/root/.cache \
>  --gpus "device=0" \
>  -p 8000:8000 \
>  wlk218 --model large-v3 --language ru --direct-english-translation
INFO:     Started server process [1]
INFO:     Waiting for application startup.
SimulStreaming will use Faster Whisper for the encoder.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     192.168.0.241:24703 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.0.241:24703 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     192.168.0.241:43873 - "WebSocket /asr" [accepted]
INFO:whisperlivekit.basic_server:WebSocket connection opened.
INFO:     connection open
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=1.68s | + Silence of = 1.68s
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.12s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.10s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.02s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.01s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s | + Silence starting | last_end = 2.28 |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.78s | + Silence of = 0.84s | last_end = 3.2 |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
INFO:whisperlivekit.audio_processor:internal_buffer=0.00s | lag=0.00s |
```

Is there possibility to enable additional logging specifically for these options (whisper backends)?
